export const countries = [
    { label: 'Afghanistan', value: 'AF', alpha3Code: 'AFG' },
    { label: 'Åland Islands', value: 'AX', alpha3Code: 'ALA' },
    { label: 'Albania', value: 'AL', alpha3Code: 'ALB' },
    { label: 'Algeria', value: 'DZ', alpha3Code: 'DZA' },
    { label: 'American Samoa', value: 'AS', alpha3Code: 'ASM' },
    { label: 'Andorra', value: 'AD', alpha3Code: 'AND' },
    { label: 'Angola', value: 'AO', alpha3Code: 'AGO' },
    { label: 'Anguilla', value: 'AI', alpha3Code: 'AIA' },
    { label: 'Antarctica', value: 'AQ', alpha3Code: 'ATA' },
    { label: 'Antigua and Barbuda', value: 'AG', alpha3Code: 'ATG' },
    { label: 'Argentina', value: 'AR', alpha3Code: 'ARG' },
    { label: 'Armenia', value: 'AM', alpha3Code: 'ARM' },
    { label: 'Aruba', value: 'AW', alpha3Code: 'ABW' },
    { label: 'Australia', value: 'AU', alpha3Code: 'AUS' },
    { label: 'Austria', value: 'AT', alpha3Code: 'AUT' },
    { label: 'Azerbaijan', value: 'AZ', alpha3Code: 'AZE' },
    { label: 'Bahamas', value: 'BS', alpha3Code: 'BHS' },
    { label: 'Bahrain', value: 'BH', alpha3Code: 'BHR' },
    { label: 'Bangladesh', value: 'BD', alpha3Code: 'BGD' },
    { label: 'Barbados', value: 'BB', alpha3Code: 'BRB' },
    { label: 'Belarus', value: 'BY', alpha3Code: 'BLR' },
    { label: 'Belgium', value: 'BE', alpha3Code: 'BEL' },
    { label: 'Belize', value: 'BZ', alpha3Code: 'BLZ' },
    { label: 'Benin', value: 'BJ', alpha3Code: 'BEN' },
    { label: 'Bermuda', value: 'BM', alpha3Code: 'BMU' },
    { label: 'Bhutan', value: 'BT', alpha3Code: 'BTN' },
    { label: 'Bolivia (Plurinational State of)', value: 'BO', alpha3Code: 'BOL' },
    { label: 'Bonaire, Sint Eustatius and Saba', value: 'BQ', alpha3Code: 'BES' },
    { label: 'Bosnia and Herzegovina', value: 'BA', alpha3Code: 'BIH' },
    { label: 'Botswana', value: 'BW', alpha3Code: 'BWA' },
    { label: 'Bouvet Island', value: 'BV', alpha3Code: 'BVT' },
    { label: 'Brazil', value: 'BR', alpha3Code: 'BRA' },
    { label: 'British Indian Ocean Territory', value: 'IO', alpha3Code: 'IOT' },
    { label: 'United States Minor Outlying Islands', value: 'UM', alpha3Code: 'UMI' },
    { label: 'Virgin Islands (British)', value: 'VG', alpha3Code: 'VGB' },
    { label: 'Virgin Islands (U.S.)', value: 'VI', alpha3Code: 'VIR' },
    { label: 'Brunei Darussalam', value: 'BN', alpha3Code: 'BRN' },
    { label: 'Bulgaria', value: 'BG', alpha3Code: 'BGR' },
    { label: 'Burkina Faso', value: 'BF', alpha3Code: 'BFA' },
    { label: 'Burundi', value: 'BI', alpha3Code: 'BDI' },
    { label: 'Cambodia', value: 'KH', alpha3Code: 'KHM' },
    { label: 'Cameroon', value: 'CM', alpha3Code: 'CMR' },
    { label: 'Canada', value: 'CA', alpha3Code: 'CAN' },
    { label: 'Cabo Verde', value: 'CV', alpha3Code: 'CPV' },
    { label: 'Cayman Islands', value: 'KY', alpha3Code: 'CYM' },
    { label: 'Central African Republic', value: 'CF', alpha3Code: 'CAF' },
    { label: 'Chad', value: 'TD', alpha3Code: 'TCD' },
    { label: 'Chile', value: 'CL', alpha3Code: 'CHL' },
    { label: 'China', value: 'CN', alpha3Code: 'CHN' },
    { label: 'Christmas Island', value: 'CX', alpha3Code: 'CXR' },
    { label: 'Cocos (Keeling) Islands', value: 'CC', alpha3Code: 'CCK' },
    { label: 'Colombia', value: 'CO', alpha3Code: 'COL' },
    { label: 'Comoros', value: 'KM', alpha3Code: 'COM' },
    { label: 'Congo', value: 'CG', alpha3Code: 'COG' },
    { label: 'Congo (Democratic Republic of the)', value: 'CD', alpha3Code: 'COD' },
    { label: 'Cook Islands', value: 'CK', alpha3Code: 'COK' },
    { label: 'Costa Rica', value: 'CR', alpha3Code: 'CRI' },
    { label: 'Croatia', value: 'HR', alpha3Code: 'HRV' },
    { label: 'Cuba', value: 'CU', alpha3Code: 'CUB' },
    { label: 'Curaçao', value: 'CW', alpha3Code: 'CUW' },
    { label: 'Cyprus', value: 'CY', alpha3Code: 'CYP' },
    { label: 'Czech Republic', value: 'CZ', alpha3Code: 'CZE' },
    { label: 'Denmark', value: 'DK', alpha3Code: 'DNK' },
    { label: 'Djibouti', value: 'DJ', alpha3Code: 'DJI' },
    { label: 'Dominica', value: 'DM', alpha3Code: 'DMA' },
    { label: 'Dominican Republic', value: 'DO', alpha3Code: 'DOM' },
    { label: 'Ecuador', value: 'EC', alpha3Code: 'ECU' },
    { label: 'Egypt', value: 'EG', alpha3Code: 'EGY' },
    { label: 'El Salvador', value: 'SV', alpha3Code: 'SLV' },
    { label: 'Equatorial Guinea', value: 'GQ', alpha3Code: 'GNQ' },
    { label: 'Eritrea', value: 'ER', alpha3Code: 'ERI' },
    { label: 'Estonia', value: 'EE', alpha3Code: 'EST' },
    { label: 'Ethiopia', value: 'ET', alpha3Code: 'ETH' },
    { label: 'Falkland Islands (Malvinas)', value: 'FK', alpha3Code: 'FLK' },
    { label: 'Faroe Islands', value: 'FO', alpha3Code: 'FRO' },
    { label: 'Fiji', value: 'FJ', alpha3Code: 'FJI' },
    { label: 'Finland', value: 'FI', alpha3Code: 'FIN' },
    { label: 'France', value: 'FR', alpha3Code: 'FRA' },
    { label: 'French Guiana', value: 'GF', alpha3Code: 'GUF' },
    { label: 'French Polynesia', value: 'PF', alpha3Code: 'PYF' },
    { label: 'French Southern Territories', value: 'TF', alpha3Code: 'ATF' },
    { label: 'Gabon', value: 'GA', alpha3Code: 'GAB' },
    { label: 'Gambia', value: 'GM', alpha3Code: 'GMB' },
    { label: 'Georgia', value: 'GE', alpha3Code: 'GEO' },
    { label: 'Germany', value: 'DE', alpha3Code: 'DEU' },
    { label: 'Ghana', value: 'GH', alpha3Code: 'GHA' },
    { label: 'Gibraltar', value: 'GI', alpha3Code: 'GIB' },
    { label: 'Greece', value: 'GR', alpha3Code: 'GRC' },
    { label: 'Greenland', value: 'GL', alpha3Code: 'GRL' },
    { label: 'Grenada', value: 'GD', alpha3Code: 'GRD' },
    { label: 'Guadeloupe', value: 'GP', alpha3Code: 'GLP' },
    { label: 'Guam', value: 'GU', alpha3Code: 'GUM' },
    { label: 'Guatemala', value: 'GT', alpha3Code: 'GTM' },
    { label: 'Guernsey', value: 'GG', alpha3Code: 'GGY' },
    { label: 'Guinea', value: 'GN', alpha3Code: 'GIN' },
    { label: 'Guinea-Bissau', value: 'GW', alpha3Code: 'GNB' },
    { label: 'Guyana', value: 'GY', alpha3Code: 'GUY' },
    { label: 'Haiti', value: 'HT', alpha3Code: 'HTI' },
    { label: 'Heard Island and McDonald Islands', value: 'HM', alpha3Code: 'HMD' },
    { label: 'Holy See', value: 'VA', alpha3Code: 'VAT' },
    { label: 'Honduras', value: 'HN', alpha3Code: 'HND' },
    { label: 'Hong Kong', value: 'HK', alpha3Code: 'HKG' },
    { label: 'Hungary', value: 'HU', alpha3Code: 'HUN' },
    { label: 'Iceland', value: 'IS', alpha3Code: 'ISL' },
    { label: 'India', value: 'IN', alpha3Code: 'IND' },
    { label: 'Indonesia', value: 'ID', alpha3Code: 'IDN' },
    { label: "Côte d'Ivoire", value: 'CI', alpha3Code: 'CIV' },
    { label: 'Iran (Islamic Republic of)', value: 'IR', alpha3Code: 'IRN' },
    { label: 'Iraq', value: 'IQ', alpha3Code: 'IRQ' },
    { label: 'Ireland', value: 'IE', alpha3Code: 'IRL' },
    { label: 'Isle of Man', value: 'IM', alpha3Code: 'IMN' },
    { label: 'Israel', value: 'IL', alpha3Code: 'ISR' },
    { label: 'Italy', value: 'IT', alpha3Code: 'ITA' },
    { label: 'Jamaica', value: 'JM', alpha3Code: 'JAM' },
    { label: 'Japan', value: 'JP', alpha3Code: 'JPN' },
    { label: 'Jersey', value: 'JE', alpha3Code: 'JEY' },
    { label: 'Jordan', value: 'JO', alpha3Code: 'JOR' },
    { label: 'Kazakhstan', value: 'KZ', alpha3Code: 'KAZ' },
    { label: 'Kenya', value: 'KE', alpha3Code: 'KEN' },
    { label: 'Kiribati', value: 'KI', alpha3Code: 'KIR' },
    { label: 'Kuwait', value: 'KW', alpha3Code: 'KWT' },
    { label: 'Kyrgyzstan', value: 'KG', alpha3Code: 'KGZ' },
    { label: "Lao People's Democratic Republic", value: 'LA', alpha3Code: 'LAO' },
    { label: 'Latvia', value: 'LV', alpha3Code: 'LVA' },
    { label: 'Lebanon', value: 'LB', alpha3Code: 'LBN' },
    { label: 'Lesotho', value: 'LS', alpha3Code: 'LSO' },
    { label: 'Liberia', value: 'LR', alpha3Code: 'LBR' },
    { label: 'Libya', value: 'LY', alpha3Code: 'LBY' },
    { label: 'Liechtenstein', value: 'LI', alpha3Code: 'LIE' },
    { label: 'Lithuania', value: 'LT', alpha3Code: 'LTU' },
    { label: 'Luxembourg', value: 'LU', alpha3Code: 'LUX' },
    { label: 'Macao', value: 'MO', alpha3Code: 'MAC' },
    { label: 'Macedonia (the former Yugoslav Republic of)', value: 'MK', alpha3Code: 'MKD' },
    { label: 'Madagascar', value: 'MG', alpha3Code: 'MDG' },
    { label: 'Malawi', value: 'MW', alpha3Code: 'MWI' },
    { label: 'Malaysia', value: 'MY', alpha3Code: 'MYS' },
    { label: 'Maldives', value: 'MV', alpha3Code: 'MDV' },
    { label: 'Mali', value: 'ML', alpha3Code: 'MLI' },
    { label: 'Malta', value: 'MT', alpha3Code: 'MLT' },
    { label: 'Marshall Islands', value: 'MH', alpha3Code: 'MHL' },
    { label: 'Martinique', value: 'MQ', alpha3Code: 'MTQ' },
    { label: 'Mauritania', value: 'MR', alpha3Code: 'MRT' },
    { label: 'Mauritius', value: 'MU', alpha3Code: 'MUS' },
    { label: 'Mayotte', value: 'YT', alpha3Code: 'MYT' },
    { label: 'Mexico', value: 'MX', alpha3Code: 'MEX' },
    { label: 'Micronesia (Federated States of)', value: 'FM', alpha3Code: 'FSM' },
    { label: 'Moldova (Republic of)', value: 'MD', alpha3Code: 'MDA' },
    { label: 'Monaco', value: 'MC', alpha3Code: 'MCO' },
    { label: 'Mongolia', value: 'MN', alpha3Code: 'MNG' },
    { label: 'Montenegro', value: 'ME', alpha3Code: 'MNE' },
    { label: 'Montserrat', value: 'MS', alpha3Code: 'MSR' },
    { label: 'Morocco', value: 'MA', alpha3Code: 'MAR' },
    { label: 'Mozambique', value: 'MZ', alpha3Code: 'MOZ' },
    { label: 'Myanmar', value: 'MM', alpha3Code: 'MMR' },
    { label: 'Namibia', value: 'NA', alpha3Code: 'NAM' },
    { label: 'Nauru', value: 'NR', alpha3Code: 'NRU' },
    { label: 'Nepal', value: 'NP', alpha3Code: 'NPL' },
    { label: 'Netherlands', value: 'NL', alpha3Code: 'NLD' },
    { label: 'New Caledonia', value: 'NC', alpha3Code: 'NCL' },
    { label: 'New Zealand', value: 'NZ', alpha3Code: 'NZL' },
    { label: 'Nicaragua', value: 'NI', alpha3Code: 'NIC' },
    { label: 'Niger', value: 'NE', alpha3Code: 'NER' },
    { label: 'Nigeria', value: 'NG', alpha3Code: 'NGA' },
    { label: 'Niue', value: 'NU', alpha3Code: 'NIU' },
    { label: 'Norfolk Island', value: 'NF', alpha3Code: 'NFK' },
    { label: "Korea (Democratic People's Republic of)", value: 'KP', alpha3Code: 'PRK' },
    { label: 'Northern Mariana Islands', value: 'MP', alpha3Code: 'MNP' },
    { label: 'Norway', value: 'NO', alpha3Code: 'NOR' },
    { label: 'Oman', value: 'OM', alpha3Code: 'OMN' },
    { label: 'Pakistan', value: 'PK', alpha3Code: 'PAK' },
    { label: 'Palau', value: 'PW', alpha3Code: 'PLW' },
    { label: 'Palestine, State of', value: 'PS', alpha3Code: 'PSE' },
    { label: 'Panama', value: 'PA', alpha3Code: 'PAN' },
    { label: 'Papua New Guinea', value: 'PG', alpha3Code: 'PNG' },
    { label: 'Paraguay', value: 'PY', alpha3Code: 'PRY' },
    { label: 'Peru', value: 'PE', alpha3Code: 'PER' },
    { label: 'Philippines', value: 'PH', alpha3Code: 'PHL' },
    { label: 'Pitcairn', value: 'PN', alpha3Code: 'PCN' },
    { label: 'Poland', value: 'PL', alpha3Code: 'POL' },
    { label: 'Portugal', value: 'PT', alpha3Code: 'PRT' },
    { label: 'Puerto Rico', value: 'PR', alpha3Code: 'PRI' },
    { label: 'Qatar', value: 'QA', alpha3Code: 'QAT' },
    { label: 'Republic of Kosovo', value: 'XK', alpha3Code: 'KOS' },
    { label: 'Réunion', value: 'RE', alpha3Code: 'REU' },
    { label: 'Romania', value: 'RO', alpha3Code: 'ROU' },
    { label: 'Russian Federation', value: 'RU', alpha3Code: 'RUS' },
    { label: 'Rwanda', value: 'RW', alpha3Code: 'RWA' },
    { label: 'Saint Barthélemy', value: 'BL', alpha3Code: 'BLM' },
    { label: 'Saint Helena, Ascension and Tristan da Cunha', value: 'SH', alpha3Code: 'SHN' },
    { label: 'Saint Kitts and Nevis', value: 'KN', alpha3Code: 'KNA' },
    { label: 'Saint Lucia', value: 'LC', alpha3Code: 'LCA' },
    { label: 'Saint Martin (French part)', value: 'MF', alpha3Code: 'MAF' },
    { label: 'Saint Pierre and Miquelon', value: 'PM', alpha3Code: 'SPM' },
    { label: 'Saint Vincent and the Grenadines', value: 'VC', alpha3Code: 'VCT' },
    { label: 'Samoa', value: 'WS', alpha3Code: 'WSM' },
    { label: 'San Marino', value: 'SM', alpha3Code: 'SMR' },
    { label: 'Sao Tome and Principe', value: 'ST', alpha3Code: 'STP' },
    { label: 'Saudi Arabia', value: 'SA', alpha3Code: 'SAU' },
    { label: 'Senegal', value: 'SN', alpha3Code: 'SEN' },
    { label: 'Serbia', value: 'RS', alpha3Code: 'SRB' },
    { label: 'Seychelles', value: 'SC', alpha3Code: 'SYC' },
    { label: 'Sierra Leone', value: 'SL', alpha3Code: 'SLE' },
    { label: 'Singapore', value: 'SG', alpha3Code: 'SGP' },
    { label: 'Sint Maarten (Dutch part)', value: 'SX', alpha3Code: 'SXM' },
    { label: 'Slovakia', value: 'SK', alpha3Code: 'SVK' },
    { label: 'Slovenia', value: 'SI', alpha3Code: 'SVN' },
    { label: 'Solomon Islands', value: 'SB', alpha3Code: 'SLB' },
    { label: 'Somalia', value: 'SO', alpha3Code: 'SOM' },
    { label: 'South Africa', value: 'ZA', alpha3Code: 'ZAF' },
    { label: 'South Georgia and the South Sandwich Islands', value: 'GS', alpha3Code: 'SGS' },
    { label: 'Korea (Republic of)', value: 'KR', alpha3Code: 'KOR' },
    { label: 'South Sudan', value: 'SS', alpha3Code: 'SSD' },
    { label: 'Spain', value: 'ES', alpha3Code: 'ESP' },
    { label: 'Sri Lanka', value: 'LK', alpha3Code: 'LKA' },
    { label: 'Sudan', value: 'SD', alpha3Code: 'SDN' },
    { label: 'Surilabel', value: 'SR', alpha3Code: 'SUR' },
    { label: 'Svalbard and Jan Mayen', value: 'SJ', alpha3Code: 'SJM' },
    { label: 'Swaziland', value: 'SZ', alpha3Code: 'SWZ' },
    { label: 'Sweden', value: 'SE', alpha3Code: 'SWE' },
    { label: 'Switzerland', value: 'CH', alpha3Code: 'CHE' },
    { label: 'Syrian Arab Republic', value: 'SY', alpha3Code: 'SYR' },
    { label: 'Taiwan', value: 'TW', alpha3Code: 'TWN' },
    { label: 'Tajikistan', value: 'TJ', alpha3Code: 'TJK' },
    { label: 'Tanzania, United Republic of', value: 'TZ', alpha3Code: 'TZA' },
    { label: 'Thailand', value: 'TH', alpha3Code: 'THA' },
    { label: 'Timor-Leste', value: 'TL', alpha3Code: 'TLS' },
    { label: 'Togo', value: 'TG', alpha3Code: 'TGO' },
    { label: 'Tokelau', value: 'TK', alpha3Code: 'TKL' },
    { label: 'Tonga', value: 'TO', alpha3Code: 'TON' },
    { label: 'Trinidad and Tobago', value: 'TT', alpha3Code: 'TTO' },
    { label: 'Tunisia', value: 'TN', alpha3Code: 'TUN' },
    { label: 'Turkey', value: 'TR', alpha3Code: 'TUR' },
    { label: 'Turkmenistan', value: 'TM', alpha3Code: 'TKM' },
    { label: 'Turks and Caicos Islands', value: 'TC', alpha3Code: 'TCA' },
    { label: 'Tuvalu', value: 'TV', alpha3Code: 'TUV' },
    { label: 'Uganda', value: 'UG', alpha3Code: 'UGA' },
    { label: 'Ukraine', value: 'UA', alpha3Code: 'UKR' },
    { label: 'United Arab Emirates', value: 'AE', alpha3Code: 'ARE' },
    { label: 'United Kingdom of Great Britain and Northern Ireland', value: 'GB', alpha3Code: 'GBR' },
    { label: 'United States of America', value: 'US', alpha3Code: 'USA' },
    { label: 'Uruguay', value: 'UY', alpha3Code: 'URY' },
    { label: 'Uzbekistan', value: 'UZ', alpha3Code: 'UZB' },
    { label: 'Vanuatu', value: 'VU', alpha3Code: 'VUT' },
    { label: 'Venezuela (Bolivarian Republic of)', value: 'VE', alpha3Code: 'VEN' },
    { label: 'Viet Nam', value: 'VN', alpha3Code: 'VNM' },
    { label: 'Wallis and Futuna', value: 'WF', alpha3Code: 'WLF' },
    { label: 'Western Sahara', value: 'EH', alpha3Code: 'ESH' },
    { label: 'Yemen', value: 'YE', alpha3Code: 'YEM' },
    { label: 'Zambia', value: 'ZM', alpha3Code: 'ZMB' },
    { label: 'Zimbabwe', value: 'ZW', alpha3Code: 'ZWE' },
  ];